### ISSUE TITLE
TS compilation error when using graphql v15

### ISSUE THREAD

**Issue by Berger92** [graphql-hive/graphql-eslint#1064]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

The plugin's package.json file [states](https://github.com/B2o5T/graphql-eslint/blob/master/packages/plugin/package.json#L56) that it is compatible with graphql version 15, but I'm having compilation errors.

Graphql version 16 changed how `Kind` is defined. They changed it from `Object` to `enum`. I am working on new rules for my project, and I am getting the following compilation errors:

```
rules/require-description.d.ts:3:327 - error TS2503: Cannot find namespace 'Kind'.
```

```
estree-converter/utils.d.ts:4:97 - error TS7016: Could not find a declaration file for module 'graphql/jsutils/ObjMap'
```

**To Reproduce**
1. Install the plugin in a new project.
2. Install graphql v15.8.0
3. Try to compile your project with `"skipLibCheck": false` option

**Expected behavior**

There wouldn't ideally be any errors with graphql version 15

**Environment:**

- OS: MacOS Monterey
- `@graphql-eslint/eslint-plugin`: 3.10.3
- Node.js: 14.19.1

**Comment by B2o5T** [comment]
For the moment we use `"skipLibCheck": true` in our `tsconfig.json` https://github.com/B2o5T/graphql-eslint/blob/master/tsconfig.json#L24
